In [58]:
import numpy as np

In [59]:
data = np.array([
    [1, 2 ,4.029],
    [2, 3 ,6.9],
    [3, 6 ,12.401],
    [4, 8 ,15.873],
    [5, 10 ,20.23],
    [6, 12 ,24.019],
    [7, 14 ,27.691],
    [8, 16 ,33],
    [9, 18 ,36.21],
    [10, 20 ,41.074]
]) 
x = data[:, 0:2].reshape(2,-1)
y = data[:, 2] 

d = x.shape[0]
n = x.shape[1]

In [60]:
print(x.shape)

(2, 10)


In [61]:
x

array([[ 1.,  2.,  2.,  3.,  3.,  6.,  4.,  8.,  5., 10.],
       [ 6., 12.,  7., 14.,  8., 16.,  9., 18., 10., 20.]])

In [62]:
x = np.vstack((np.ones(n),x))
d = x.shape[0]
n = x.shape[1]
x

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  2.,  2.,  3.,  3.,  6.,  4.,  8.,  5., 10.],
       [ 6., 12.,  7., 14.,  8., 16.,  9., 18., 10., 20.]])

In [63]:
y

array([ 4.029,  6.9  , 12.401, 15.873, 20.23 , 24.019, 27.691, 33.   ,
       36.21 , 41.074])

In [64]:
def updation(w,x,y):
    return 2*(x @ x.T) @ w - 2 * x @ np.expand_dims(y,axis=1)

In [65]:
w_updated,w_ini = np.zeros((d,1)) , np.zeros((d,1))

for i in range(500):
    print(w_ini)
    w_updated = w_ini - (0.0001 / 3) * (updation(w_ini,x,y))
    w_ini = w_updated

print(w_updated)

[[0.]
 [0.]
 [0.]]
[[0.0147618 ]
 [0.0841072 ]
 [0.19926307]]
[[0.02767294]
 [0.15821963]
 [0.37292296]]
[[0.0389688 ]
 [0.22360686]
 [0.5242346 ]]
[[0.04885483]
 [0.2813771 ]
 [0.65603918]]
[[0.05751037]
 [0.33249766]
 [0.77081671]]
[[0.06509197]
 [0.37781291]
 [0.87073195]]
[[0.07173627]
 [0.41805988]
 [0.9576745 ]]
[[0.07756254]
 [0.45388192]
 [1.03329375]]
[[0.08267489]
 [0.48584059]
 [1.09902941]]
[[0.08716421]
 [0.51442608]
 [1.1561382 ]]
[[0.09110981]
 [0.54006626]
 [1.20571708]]
[[0.09458094]
 [0.56313461]
 [1.24872358]]
[[0.09763804]
 [0.58395716]
 [1.2859935 ]]
[[0.10033386]
 [0.60281846]
 [1.31825639]]
[[0.10271445]
 [0.61996692]
 [1.34614908]]
[[0.10482001]
 [0.63561936]
 [1.37022744]]
[[0.10668563]
 [0.64996505]
 [1.39097667]]
[[0.10834193]
 [0.66316918]
 [1.4088203 ]]
[[0.10981564]
 [0.67537598]
 [1.42412802]]
[[0.1111301 ]
 [0.68671131]
 [1.43722254]]
[[0.11230568]
 [0.69728505]
 [1.44838553]]
[[0.11336016]
 [0.70719311]
 [1.45786285]]
[[0.11430905]
 [0.71651922]
 [1.465

In [66]:
x_new = np.array([1,9,9])
x_new.T @ w_updated

array([31.14506354])