In [35]:
import numpy as np

In [36]:
data = np.array([
    [1, 2],
    [2, 3.9],
    [3, 5.8],
    [4, 8.1],
    [5, 9.9],
    [6, 12.3],
    [7, 14.1],
    [8, 16.5],
    [9, 18.2],
    [10, 20.4]
]) 
x = data[:, 0].reshape(1,-1)
y = data[:, 1] 

d = x.shape[0]
n = x.shape[1]

In [37]:
print(x.shape)

(1, 10)


In [38]:
x = np.vstack((np.ones(n),x))
d = x.shape[0]
n = x.shape[1]
x

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [39]:
x.shape

(2, 10)

In [40]:
def updation(w,x,y):
    return 2*(x @ x.T) @ w - 2 * x @ np.expand_dims(y,axis=1)

In [41]:
w_updated,w_ini = np.zeros((d,1)) , np.zeros((d,1))

for i in range(1000):
    print(w_ini)
    w_updated = w_ini - (0.001 / 3) * (updation(w_ini,x,y))
    w_ini = w_updated

print(w_updated)

[[0.]
 [0.]]
[[0.07413333]
 [0.52093333]]
[[0.12867156]
 [0.90544222]]
[[0.16874753]
 [1.18926076]]
[[0.19814965]
 [1.39876309]]
[[0.21967401]
 [1.55341508]]
[[0.2353843 ]
 [1.66758383]]
[[0.24680366]
 [1.75187322]]
[[0.25505628]
 [1.81410963]]
[[0.26097189]
 [1.86006943]]
[[0.26516286]
 [1.89401597]]
[[0.26808119]
 [1.9190959 ]]
[[0.27006047]
 [1.93763164]]
[[0.27134691]
 [1.9513373 ]]
[[0.27212222]
 [1.96147801]]
[[0.27252055]
 [1.9689875 ]]
[[0.27264087]
 [1.97455496]]
[[0.27255625]
 [1.97868902]]
[[0.27232061]
 [1.98176511]]
[[0.27197375]
 [1.98406031]]
[[0.27154505]
 [1.98577913]]
[[0.27105618]
 [1.9870725 ]]
[[0.27052315]
 [1.98805183]]
[[0.26995776]
 [1.98879935]]
[[0.26936873]
 [1.98937573]]
[[0.2687625 ]
 [1.98982577]]
[[0.2681438 ]
 [1.99018253]]
[[0.26751615]
 [1.99047041]]
[[0.26688213]
 [1.99070741]]
[[0.26624364]
 [1.99090683]]
[[0.2656021 ]
 [1.99107848]]
[[0.26495854]
 [1.99122959]]
[[0.26431373]
 [1.99136552]]
[[0.26366824]
 [1.9914902 ]]
[[0.26302248]
 [1.99160654]]
[

In [45]:
x_new = np.array([1,100])
x_new.T @ w_updated

array([204.01913114])