In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression


In [2]:
X = np.array([[1,1,1,1,1],[1,3,4,6,7],[10,14,15,18,20]])
Y = np.array([9,10,13,14,16])

In [3]:
t = X @ X.T
print(t)
np.linalg.det(t)

[[   5   21   77]
 [  21  111  360]
 [  77  360 1245]]


51.000000000009216

In [4]:
np.linalg.inv(t)

array([[168.52941176,  30.88235294, -19.35294118],
       [ 30.88235294,   5.80392157,  -3.58823529],
       [-19.35294118,  -3.58823529,   2.23529412]])

In [5]:
w = np.linalg.pinv(X @ X.T) @ X @ np.expand_dims(Y,axis = 1)

In [6]:
w

array([[17.17647059],
       [ 2.96078431],
       [-1.11764706]])

In [7]:
x1 = np.array([1,1,20])

In [8]:
x1.T @ w

array([-2.21568627])