<h1>Linear Regression</h1>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
X = np.array([[1,1,1,1,1],[1,3,4,6,7],[10,14,15,18,20]])
Y = np.array([9,10,13,14,16])

In [3]:
t = X @ X.T
print(t)
np.linalg.det(t)

[[   5   21   77]
 [  21  111  360]
 [  77  360 1245]]


51.000000000009216

In [4]:
np.linalg.inv(t)

array([[168.52941176,  30.88235294, -19.35294118],
       [ 30.88235294,   5.80392157,  -3.58823529],
       [-19.35294118,  -3.58823529,   2.23529412]])

In [5]:
w = np.linalg.pinv(X @ X.T) @ X @ np.expand_dims(Y,axis = 1)

In [6]:
w

array([[17.17647059],
       [ 2.96078431],
       [-1.11764706]])

In [7]:
x1 = np.array([1,1,20])

In [8]:
x1.T @ w

array([-2.21568627])

<h1>Gradient Descent</h1>

In [9]:
import numpy as np

In [10]:
data = np.array([
    [1, 2 ,4.029],
    [2, 3 ,6.9],
    [3, 6 ,12.401],
    [4, 8 ,15.873],
    [5, 10 ,20.23],
    [6, 12 ,24.019],
    [7, 14 ,27.691],
    [8, 16 ,33],
    [9, 18 ,36.21],
    [10, 20 ,41.074]
]) 
x = data[:, 0:2].reshape(2,-1)
y = data[:, 2] 
# y = 2*x1 + x2 + noise
d = x.shape[0]
n = x.shape[1]

In [11]:
x = np.vstack((np.ones(n),x))
d = x.shape[0]
n = x.shape[1]
x

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  2.,  2.,  3.,  3.,  6.,  4.,  8.,  5., 10.],
       [ 6., 12.,  7., 14.,  8., 16.,  9., 18., 10., 20.]])

In [12]:
def derivative(w,x,y):
    return 2*(x @ x.T) @ w - 2 * x @ np.expand_dims(y,axis=1)

In [13]:
def gradient_descent(w_old,x,y,learning_rate,iterations):
    w_new = np.zeros((x.shape[0],1))
    for i in range(iterations):
        print(w_old)
        w_new = w_old - (learning_rate / 3) * (derivative(w_old,x,y))
        w_old = w_new
    return w_old

In [14]:
w_old = np.zeros((x.shape[0],1))
w = gradient_descent(w_old,x,y,learning_rate=0.001,iterations=100)

[[0.]
 [0.]
 [0.]]
[[0.147618  ]
 [0.841072  ]
 [1.99263067]]
[[0.11016998]
 [0.68266694]
 [1.42494363]]
[[0.12303313]
 [0.79436136]
 [1.55187192]]
[[0.12237989]
 [0.8319048 ]
 [1.49079161]]
[[0.12551615]
 [0.88865769]
 [1.48103348]]
[[0.12774741]
 [0.93931618]
 [1.45769517]]
[[0.13034487]
 [0.99075368]
 [1.4383713 ]]
[[0.13296209]
 [1.04111814]
 [1.41828639]]
[[0.1356913 ]
 [1.09092338]
 [1.39873097]]
[[0.1385058 ]
 [1.14004153]
 [1.37935075]]
[[0.14141114]
 [1.18851856]
 [1.36023752]]
[[0.14440419]
 [1.23635314]
 [1.34136216]]
[[0.14748417]
 [1.28355663]
 [1.32272838]]
[[0.15064967]
 [1.33013681]
 [1.30433108]]
[[0.15389951]
 [1.37610227]
 [1.28616758]]
[[0.15723244]
 [1.42146122]
 [1.26823459]]
[[0.16064726]
 [1.46622187]
 [1.25052905]]
[[0.16414278]
 [1.51039226]
 [1.23304791]]
[[0.16771782]
 [1.55398034]
 [1.21578814]]
[[0.17137123]
 [1.59699396]
 [1.19874676]]
[[0.17510186]
 [1.63944085]
 [1.18192085]]
[[0.17890858]
 [1.68132866]
 [1.16530751]]
[[0.18279028]
 [1.7226649 ]
 [1.148

In [15]:
x_new = np.array([1,9,18])
x_new.T @ w

array([40.16727273])

<h1>Logistic Regression</h1>